### ISSUE TITLE
Doladiť základné nastavenia

### ISSUE THREAD

**Issue by MartinHlavna** [MartinHlavna/hector#52]
Treba sa ešte raz pozrieť na hodnoty, ktoré sú v základných nastaveniach a určiť hodnoty, ktoré sú "good-enough". Väčšina userov si asi nebude nastavenia prispôsobovať.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Adjusted default values in the AnalysisSettings class to provide better out-of-the-box experience for most users. Changes include:
1. Increased minimum word length for repeated words and close words analysis
2. Adjusted sentence length thresholds for mid and high
3. Increased minimum distance between close words
4. Enabled all analysis features by default

You can review changes in this commit: https://github.com/lkilu6456546/MartinHlavna-hector-52/commit/97ff14a7c08be7ff6dbc487accefe0cf7be930fa.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by MartinHlavna** [comment]
Zatiaľ navýšená tolerancia opakovania na 3 opakovania v priebehu asi tretiny strany.

**Comment by MartinHlavna** [comment]
Návrh z vydavateľstva Príbeh:

15 slov a 2 opakovania. Treba získať ešte väčší feedback a na základe toho sa rozhodnúť.

**Comment by MartinHlavna** [comment]
Ponechávam momentálne nastavenia.
